Iter13
tiunovvv/go-yandex-shortener pull request #13
Opened 2023-12-07 12:50 UTC by tiunovvv

2023-12-08 15:24 UTC, s-shpak requested changes

2023-12-08 15:24 UTC, s-shpak commented on internal/storage/query-tracer.go
Лучше называть файлы единообразно: лиюо через дефисы, либо через нижнее подчеркивание

2023-12-08 15:24 UTC, s-shpak commented on internal/storage/db.go
> +) (shortener.Store, error) {
Импортирование интерфейса со слоя верхнего уровня является нарушением принципа однонаправленности завиимостей.

Можно определить интерфейсы и здесь, и на верхнем уровне

2023-12-08 15:24 UTC, s-shpak commented on internal/storage/db.go
> +	createSchemaURLs :=
Надо будет поменять на миграции после сегодняшнего вебинара

2023-12-08 15:24 UTC, s-shpak commented on internal/storage/db.go
> +	insertSchemaURLs :=
Запросы могут быть константами

2023-12-08 15:24 UTC, s-shpak commented on internal/storage/db.go
> +	*generator.Generator
Не очень понимаю, зачем помещать (и встраивать) генератор в `Store`: по идее стор не должен генерировать ID, он должен их принимать извне

2023-12-08 15:24 UTC, s-shpak commented on internal/handler/handler.go
> +		shortURLSlice[i].ShortURL = h.config.BaseURL + "/" + shortURLSlice[i].ShortURL
Лучше собирать строку через `fmt.Sprintf`

2023-12-08 15:24 UTC, s-shpak commented on internal/storage/in_memory.go
>  type InMemoryStore struct {
Не понятно зачем экспортировать `InMemoryStore`, если все равно везде используется `FileStore` с `file == nil`.

Вообще говоря, мне не очень нравится такой дизайн: в идеале реализация должна быть спрятана от верхнего уровня за единым интрефейсом, примерно так, как я описывал здесь: https://app.pachca.com/chats/7545460?message=104649294

2023-12-08 15:24 UTC, s-shpak commented on internal/server/server.go
> +	ctx, cancelCtx := context.WithTimeout(context.TODO(), seconds)
`context.TODO` используется исключительно как заглушка, необходимо вместо него использовать `context.Background()`.

Контекст лучше инициализировать где-нибудь в `main` и передавать в эту функцию первым аргументом

2023-12-08 15:24 UTC, s-shpak commented on internal/server/server.go
> +		store = storage.NewFileStore(config, logger)
Если в конфигурации запрашивается взаимодействие с DB, то делать fallback на другой стор в случае ошибки кажется плохой идеей. Лучше просто возвращай ошибку

2023-12-08 15:24 UTC, s-shpak commented on internal/server/server.go
> +	const seconds = 10 * time.Second
Мне не кажется обязательным прикручивать автоматический таймаут здесь: лучше это будет сделать через пользовательское прерывание, как разберем в следующем спринте

2023-12-08 15:24 UTC, s-shpak commented on internal/shortener/shortener.go
> +	const seconds = time.Second * 10
Лучше регулировать таймаут на уровне `http.Server` при помощи параметра конфигурации `WriteTimeout`. Либо, если необходима более гранулированная логика, на уровне хендлера

2023-12-08 15:24 UTC, s-shpak commented on internal/storage/db.go
> +func (db *DataBase) CloseStore() error {
Лучше переименовать в `Close` - из контекста понятно, что закрывается именно `Store`

2023-12-08 15:24 UTC, s-shpak commented on internal/storage/db.go
> +func (db *DataBase) stringToChar8(input string) string {
В Go это можно делать через `[]byte(str)`

2023-12-14 10:17 UTC, s-shpak requested changes

2023-12-14 10:17 UTC, s-shpak commented on internal/storage/store.go
> +	GenerateShortURL() string
Странно, что хранилище генерирует ID, этим должна заниматься бизнес-логика. Кроме того странно, что каждая БД может по-своему создавать ID, логика не должна зависеть от имплементации хранилища

2023-12-14 10:17 UTC, s-shpak commented on internal/storage/db_memory.go
`db_memory` -> `db`

2023-12-14 10:17 UTC, s-shpak commented on internal/storage/file_memory.go
`file_memory` -> `file`

2023-12-14 10:17 UTC, s-shpak commented on internal/storage/in_memory.go
`in_memory` -> `memory`

2023-12-14 10:17 UTC, s-shpak commented on internal/storage/in_memory.go
> +func (i *InMemoryStore) GetPing(ctx context.Context) error {
Кажется, что пинг не должен возвращать ошибку здесь: хранилище просто должно возвращать `nil`

2023-12-14 10:17 UTC, s-shpak commented on internal/shortener/shortener.go
> +	const seconds = time.Second * 10
Я не советовал бы выставлять timeout'ы так. Посмотри, какие варианты есть: https://ieftimov.com/posts/make-resilient-golang-net-http-servers-using-timeouts-deadlines-context-cancellation/

Я бы, в частности, обратил внимание на https://pkg.go.dev/net/http#TimeoutHandler

2023-12-14 10:17 UTC, s-shpak commented on internal/handler/handler.go
> +	shortURL, err := h.shortener.GetShortURL(c, fullURL)
А ты не мог бы напомнить, где в ТЗ находится требование о том, что `fullURL` не должны повторяться в БД ?

2023-12-15 09:06 UTC, s-shpak requested changes

2023-12-15 09:06 UTC, s-shpak commented on internal/shortener/shortener.go
> +func (sh *Shortener) generateShortURL() string {
В этом методе никак не используется ресивер, так что можно заменить на функцию

2023-12-15 09:06 UTC, s-shpak commented on internal/handler/handler.go
> +	router.POST("/", h.timeoutHandler(seconds, timeOutMsg), h.PostHandler)
Кажется, что можно:
1. убрать эту логику в middleware
2. просто использовать https://pkg.go.dev/net/http#TimeoutHandler , чем он тебя не устроил ?

2023-12-15 09:24 UTC, tiunovvv commented on internal/handler/handler.go
> +	shortURL, err := h.shortener.GetShortURL(c, fullURL)
Такого требования действительно нет, я убрал эту логику из всех store. Оставил только проверку на наличие в  store, чтобы вернуть статус 409. Вот условие из задания 13 инкремента:
```
При попытке пользователя сократить уже имеющийся в базе URL через хендлеры POST / и POST /api/shorten сервис должен вернуть HTTP-статус 409 Conflict, а в теле ответа — уже имеющийся сокращённый URL в правильном для хендлера формате.
```

2023-12-15 09:25 UTC, tiunovvv commented on internal/handler/handler.go
> +	router.POST("/", h.timeoutHandler(seconds, timeOutMsg), h.PostHandler)
Функция `TimeoutHandler` возвращает объект типа `Handler`, а в методах `POST` и `GET` на вход нужно было подать gin.HandlerFunc, поэтому написал свою функцию. Уберу в middleware, вчера не додумался до этого

2023-12-15 11:34 UTC, s-shpak approved these changes

2024-01-28 12:54 UTC, merged