Iter15
tiunovvv/go-yandex-shortener pull request #15
Opened 2023-12-25 13:41 UTC by tiunovvv

2023-12-27 00:38 UTC, s-shpak requested changes

2023-12-27 00:38 UTC, s-shpak commented on cmd/shortener/main.go
> +	cancelCtx()
`cancelCtx` принято завершать в `defer`. Можно поместить этот вызов под строкой 13

2023-12-27 00:38 UTC, s-shpak commented on cmd/shortener/main.go
> +	ctx, cancelCtx := context.WithTimeout(context.Background(), seconds)
Сейчас твой контекст завершится через 10 секунд после старта программы. Кажется, что это некорректно. Пока у тебя нет graceful shutdown, можешь просто использовать `context.Background` как корневой контекст

2023-12-27 00:38 UTC, s-shpak commented on internal/config/config.go
> +	dsn := flag.String("d", "postgres://postgres:postgres@localhost:5432/praktikum?sslmode=disable", "db adress")
Не стоит помещать дефолтный `dsn` в код -- в этой строке могут быть конфиденциальные данные

2023-12-27 00:38 UTC, s-shpak commented on internal/handler/handler.go
> +	fullShortURL := fmt.Sprintf("%s%s%s", h.config.BaseURL, c.Request.URL.RequestURI(), shortURL)
Для этого лучше использовать https://pkg.go.dev/net/url#JoinPath

2023-12-27 00:38 UTC, s-shpak commented on internal/handler/handler.go
> +	shortURLSlice, err := h.shortener.GetShortURLBatch(c, fullURLSlice, fmt.Sprintf("%v", userID))
Не надо использовать `fmt.Sprintf` для `userID`. Тебе стоит сделать `type assertion` на полученном `userID`, чтобы убедиться, что там действительно строка

2023-12-27 00:38 UTC, s-shpak commented on internal/handler/handler_test.go
> +			ctx, cancelCtx := context.WithTimeout(context.TODO(), seconds)
Не надо использовать `context.TODO` здесь -- он только для того, чтобы пометить контекст, который будет заменен в дальнейшем. Используй `context.Background`

2023-12-27 00:38 UTC, s-shpak commented on internal/middleware/cookie.go
> +func SetCookie(log *zap.Logger) gin.HandlerFunc {
Cookie должна быть подписана

2023-12-27 00:38 UTC, s-shpak commented on internal/middleware/timeout.go
> +		done := make(chan bool, 1)
Обычно просто создается небуферизованный канал типа `struct{}`, который закрывается в `defer` после выполнения функции. Это и является индикатором

2023-12-27 00:38 UTC, s-shpak commented on internal/shortener/shortener.go
> +	userID string) ([]models.ResAPIBatch, error) {
```suggestion
	userID string,
) ([]models.ResAPIBatch, error) {
```

2023-12-27 00:38 UTC, s-shpak commented on internal/shortener/shortener.go
> +func (sh *Shortener) SetDeletedFlag(ctx context.Context, userID string, shortURLSlice []string) {
Это не асинхронная обработка: ты будешь ждать, пока ты сможешь записать все задачи в канал для воркеров. Чтобы сделать по ТЗ, тебе надо принять списк url на удаление, запустить в отдельной горутине диспетчер, который будете передавать задачи воркерам, запустить воркеры, и выйти из хендлера

2023-12-27 00:38 UTC, s-shpak commented on internal/storage/db.go
> +func (db *DB) SaveURL(ctx context.Context, shortURL string, fullURL string, userID string) error {
А как понять, что такой `shortURL` уже существует, и необходимо перегенерировать его ? Такой же вопрос для `fullURL`

2023-12-27 00:38 UTC, s-shpak commented on internal/storage/db.go
> +	for k, v := range urls {
Это не батчинг. Почитай про то, что такое батчинг, и используй https://pkg.go.dev/github.com/jackc/pgx/v5#Batch

2023-12-27 00:38 UTC, s-shpak commented on internal/storage/db.go
> +			if tx.Rollback(ctx) != nil {
Ты можешь поместить `Rollback` в `defer` после строки 120. Если ты закоммитишься раньше, то `Rollback` ничего не сделает

2023-12-27 00:38 UTC, s-shpak commented on internal/storage/db.go
> +	rows, err := db.pool.Query(ctx, selectSchemaURLsByUserID, userID)
`rows` необходимо закрывать

2023-12-27 00:38 UTC, s-shpak commented on internal/storage/migrations/00001_init.up.sql
> +    full_url VARCHAR(200) NOT NULL);
Я, возможно, не обратил на это внимаени в предыдущем спринте, но у тебя, похоже, не реализован инкремент 13. Это надо сделать

2024-01-11 23:08 UTC, tiunovvv commented on internal/middleware/cookie.go
> +func SetCookie(log *zap.Logger) gin.HandlerFunc {
Подписал куки в handler.go в строке 49

2024-01-12 09:34 UTC, s-shpak commented on cmd/shortener/main.go
> +	cancelCtx()
Теперь вызов `cancelCtx` вообще пропал. Даже если ты вызываешь его где-то дальше, принято добавлять `defer cancelCtx` после создания контекста - это не является ошибкой

2024-01-12 09:40 UTC, s-shpak commented on internal/shortener/shortener.go
> +	userID string) ([]models.ResAPIBatch, error) {
Ты не хочешь отформатировать код таким образом?

2024-01-12 09:46 UTC, s-shpak requested changes

2024-01-12 09:46 UTC, s-shpak commented on internal/shortener/shortener.go
> +	jobQueue := make(chan Job, len(shortURLSlice))
Это неправильно, каналы не должны быть произвольного размера. Для воркер пула емкость канала джоб должна совпадать с количеством воркеров.

2024-01-12 14:14 UTC, tiunovvv commented on cmd/shortener/main.go
> +	cancelCtx()
GitHub странно отобразил изменения, если смотреть весь код последнего commit

main.go
```
	ctx, cancelCtx := context.WithCancel(context.Background())

	server, err := server.NewServer(ctx)
	if err != nil {
		log.Fatalf("error building server: %v", err)
	}

	if err := server.Start(cancelCtx); err != nil {
		log.Fatalf("error starting server: %v", err)
	}
```
golangci-lint ругался на defer cancelCtx(), так как есть log.Fatalf("error starting server: %v", err),
я передал cancelCtx в server.Start и вызвал defer cancel() в начале Start

server.go
```
func (s *Server) Start(cancel context.CancelFunc) error {
	defer cancel()
```

2024-01-14 14:30 UTC, s-shpak commented on cmd/shortener/main.go
> +	cancelCtx()
Добавлять defer сразу после создания контекста - хорошая практика, это дает больше гарантий, что ты не забудешь закрыть контекст. Линтер тоже ругается логично. Похоже, что надо изменить код. Такая ситуация иллюстрирует причину, почему я всегда рекомендую писать точку входа примерно таким образом:

```go
func main() {
    if err := run(); err != nil {
        log.Fatalf(err)
    }
}

func run() error {
    ...
}
```

2024-01-14 14:32 UTC, s-shpak requested changes
См. последний комментарий

2024-01-15 13:11 UTC, s-shpak approved these changes

2024-01-28 12:54 UTC, merged