Iter18
tiunovvv/go-yandex-shortener pull request #17
Opened 2024-02-28 02:46 UTC by tiunovvv

2024-02-29 17:14 UTC, s-shpak requested changes
Сейчас покрытие кода -- 27.5%, см. здесь как его можно расчитать: https://stackoverflow.com/questions/33444968/how-to-get-all-packages-code-coverage-together-in-go. Необходимо довести его до >= 40%

В остальном все выполнено хорошо

2024-03-06 10:38 UTC, s-shpak requested changes
Покрытие тестами = 37.5%, должно быть >= 40%

2024-03-07 16:48 UTC, tiunovvv commented
Запускаю команды 
go test -v -coverpkg=./... -coverprofile=profile.cov ./...  
go tool cover -func profile.cov

Довел до 45.6%
![image](https://github.com/tiunovvv/go-yandex-shortener/assets/43812677/7f69ce32-56fa-4864-80c1-c7e5aefab6b7)

2024-03-09 19:19 UTC, s-shpak approved these changes
Странно, ты не мог бы прислать мне твой `profile.cov`, пожалуйста ? После последнего коммита покрытие = 41.3%, так что работу я принимаю. Но все же хотелось бы разобраться, откуда эта разница

2024-06-12 15:53 UTC, merged