Iter5
tiunovvv/go-yandex-shortener pull request #5
Opened 2023-11-03 19:43 UTC by tiunovvv

2023-11-04 17:08 UTC, s-shpak requested changes
Ты послал ссылку не на PR, а на конкретный коммит. Это не очень страшно, но в следующий раз присылай, пожалуйста, правильную

2023-11-04 17:08 UTC, s-shpak commented on cmd/client/main.go
Тебе не понадобится код клиента, советую его удалить. Если ты хочешь тестировать приложене, то используй `curl`, например

2023-11-04 17:08 UTC, s-shpak commented on go.sum
Необходимо обновить, использовав `go mod tidy`

2023-11-04 17:08 UTC, s-shpak commented on cmd/config/config.go
> +	*ServerStartURL
Зачем ты встраиваешь эти два объекта в объект конфигурации? Почему ты используешь указатели?

2023-11-04 17:08 UTC, s-shpak commented on cmd/config/config.go
> +type ServerStartURL struct {
Зачем ты определяешь отдельный тип и разбиваешь его на два поля? Почему просто не представить это как строку?

2023-11-04 17:08 UTC, s-shpak commented on cmd/shortener/main.go
> +	"github.com/sirupsen/logrus"
Я бы не советовал использовать logrus, его больше не развивают. Посмотри в сторону `zap`, `zerolog` или какого-либо другого логгера

2023-11-04 17:08 UTC, s-shpak commented on cmd/shortener/main.go
> +		logrus.Fatalf("error occured while running http server: %s", err.Error())
```suggestion
		logrus.Fatalf("error occured while running http server: %v", err)
```

2023-11-04 17:08 UTC, s-shpak commented on cmd/config/config.go
> +	TLS  string
Т.к. TLS использовать сейчас невозможно, это надо убрать из конфигурации

2023-11-04 17:08 UTC, s-shpak commented on pkg/handler/handler.go
> +	bodyIsInitial = "Body is initial"
Если константы используются только один раз, необязательно выносить их в отдельный блок на уровне пакета

2023-11-04 17:08 UTC, s-shpak commented on pkg/handler/handler.go
> +	router := gin.New()
В первом спринте не нужно пользоваться фреймворками для роутинга

2023-11-04 17:08 UTC, s-shpak commented on pkg/handler/handler.go
> +		newErrorResponce(c, http.StatusBadRequest, err.Error())
Это не bad request, это внутренняя ошибка сервиса, а значит клиенту не надо знать, почему она произошла

2023-11-04 17:08 UTC, s-shpak commented on pkg/handler/handler.go
> +		newErrorResponce(c, http.StatusBadRequest, bodyIsInitial)
```suggestion
		newErrorResponse(c, http.StatusBadRequest, bodyIsInitial)
```

2023-11-04 17:08 UTC, s-shpak commented on pkg/handler/response.go
> +	logrus.Error(message)
Надо ли нам логировать любые ошибки?

2023-11-04 17:08 UTC, s-shpak commented on pkg/storage/storage.go
> +func GenerateShortURL() ([]byte, error) {
Почему объект `Storage` генерирует короткий URL, кажется, что этим должна заниматься бизнес-логика

2023-11-04 17:08 UTC, s-shpak commented on pkg/storage/storage.go
> +func AppendToMap(u *URLShortener, url []byte) ([]byte, error) {
Не стоит называть методы так, чтобы становилось понятным, как они устроены внутри

2023-11-04 17:08 UTC, s-shpak commented on pkg/storage/storage.go
> +		u.Urls[stringShortURL] = string(url)
А что если такой `stringShortURL` уже есть в мапе?

2023-11-04 17:08 UTC, s-shpak commented on pkg/storage/storage.go
> +	"crypto/rand"
Достаточно `math/rand`

2023-11-04 17:08 UTC, s-shpak commented on pkg/storage/storage.go
> +		ret[i] = charset[num.Int64()]
Когда перейдешь на `math/rand` преобразования типов станут ненужны

2023-11-04 17:08 UTC, s-shpak commented on pkg/storage/storage.go
> +	} else {
Этот `else` не нужен

2023-11-04 17:08 UTC, s-shpak commented on pkg/storage/storage.go
> +		return fullURLByte, fmt.Errorf(urlNotFound)
В ошибку лучше добавлять информацию о том почему ошибка произошла. Кроме того константа не нужна

```suggestion
		return fullURLByte, fmt.Errorf("URL \"%s\" not found", shortURL)
```

2023-11-04 17:08 UTC, s-shpak commented on pkg/storage/storage.go
> +func GetFullURL(u *URLShortener, shortURL string) ([]byte, error) {
Почему не объявить это (и другие функции пакета) методом `URLShortener` ?

2023-11-08 14:52 UTC, s-shpak requested changes

2023-11-08 14:52 UTC, s-shpak commented on internal/config/config.go
> +func checkServerAddress(str string) bool {
Я бы не стал помещать эту логику в пакет конфигурации: в пакете конфигурации мы просто получаем параметры, передаваемые пользователем, а их валидацией должна заниматься логика, использующая их

2023-11-08 14:52 UTC, s-shpak commented on internal/config/config.go
> +		fmt.Printf("%s is not in a form host:port", str)
Если мы передадим строку `http://127.0.0.1:8080`, то она не пройдет провреку, хотя это неверно

Я бы вообще не стал валидировать адрес, а просто пытался бы запустить сервер, используя его. Если не получится, то выкинем ошибку

2023-11-08 14:52 UTC, s-shpak commented on internal/config/config.go
> +		fmt.Printf("Port %s must have 4 digits", substr[1])
Используй `log` для таких сообщений

2023-11-08 14:52 UTC, s-shpak commented on internal/handler/handler.go
> +		fmt.Printf("%s is not URL", fullURL)
Надо использовать логгер

2023-11-08 14:52 UTC, s-shpak commented on pkg/storage/storage.go
> +		u.Urls[stringShortURL] = string(url)
Это пока не сделано

2023-11-08 16:55 UTC, tiunovvv commented on pkg/storage/storage.go
> +		u.Urls[stringShortURL] = string(url)
Сделал это в бизнес логике 
в internal/shortener/shortener.go 
строки 26-29 
```go
shortURL := sh.GenerateShortURL()
for sh.storage.FindByShortURL(shortURL) {
    shortURL = sh.GenerateShortURL()
}
```
перед вызовом метода SaveURL генерирую уникальный URL

2023-11-09 11:21 UTC, s-shpak commented on pkg/storage/storage.go
> +		u.Urls[stringShortURL] = string(url)
Это стоит сделать иначе: тебе надо генерировать уникальный ID, пытаться его записать в сторэдж. Если это не получается, потому что ID уже есть (здесь надо проверить ошибку), то надо повторить операцию

2023-11-09 11:23 UTC, s-shpak requested changes
См. комментарий к последнему оставшемуся треду

2023-11-09 18:48 UTC, tiunovvv commented
Дополнительно проверил все через golangci-lint и избавился от ошибок

2023-11-13 13:53 UTC, s-shpak requested changes

2023-11-13 13:53 UTC, s-shpak commented on internal/shortener/shortener.go
> +	for sh.storage.SaveURL(fullURL, shortURL) != nil {
Поправь проверку ошибки: ошибка может быть не только из-за коллизии. Проверить ошибку можно через `errors.Is` (правильнее) или через текст ошибки (хуже, но тоже работает).

Если выберешь первый вариант, то создай ошибку в пакете `errors`

2023-11-13 19:18 UTC, s-shpak requested changes

2023-11-13 19:18 UTC, s-shpak commented on internal/errors/errors.go
> +func (e *KeyAlreadyExistsError) Error() string {
Это не требуется, вобщем-то. Можно сделать так:

1. Объявляешь ошибку 

```go
var ErrKeyAlreadyExists = errors.New("key already exists")
```

2. Возвращаешь ее так:

```go
return fmt.Errorf("cannot save shortURL %s: %w", shortURL, ErrKeyAlreadyExists)
```

3. Проверяешь ошибку при помощи `errors.Is`

Чтобы понять, как это работает почитай https://go.dev/blog/go1.13-errors

2023-11-13 19:18 UTC, s-shpak commented on internal/storage/storage.go
> +		return &errors.KeyAlreadyExistsError{Key: key}
Ключем здесь будет не `key`, а `shortURL`

2023-11-15 20:08 UTC, s-shpak approved these changes

2023-11-15 20:35 UTC, merged